### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by jhx646018057** [wangx1996/Cascaded-Lidar-Ground-Segmentation#1]
when I install the package, and perform "make", there is :
`
[100%] Linking CXX executable test1
/usr/bin/ld: 找不到 -lefence
collect2: error: ld returned 1 exit status
CMakeFiles/test1.dir/build.make:408: recipe for target 'test1' failed
make[2]: *** [test1] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/test1.dir/all' failed
make[1]: *** [CMakeFiles/test1.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`
what should i do to resolve the problem?

**Comment by wangx1996** [comment]
@jhx646018057 删掉cmakelists里的-lefence

**Comment by jhx646018057** [comment]
@wangx1996 谢谢，问题解决了
